### ISSUE TITLE
Build problems rtmidi 4.0.0

### ISSUE THREAD

**Issue by IOTeule** [tsmetana/mpk3-settings#11]
I have problems building on Ubuntu 20.04.6 LTS

No package 'rtmidi' found

1) sudo apt install librtmidi-dev gives an error about missing librtaudio-dev
2) sudo apt install librtmidi-dev 2nd works, but install only 3.0.0

Any idea ?

```
checking for RTMIDI5... no
checking for RTMIDI4... no
configure: error: Package requirements (rtmidi >= 4.0.0) were not met:

Requested 'rtmidi >= 4.0.0' but version of librtmidi is 3.0.0

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.
```

Thx a lot

**Comment by IOTeule** [comment]
I am small step further.
Compiled and installed latest rtmidi from code, now I get error, guess its kind of a version conflict ?

```
device.c: In function ‘dump_buffer_data’:
device.c:34:7: warning: implicit declaration of function ‘g_log_get_debug_enabled’; did you mean ‘g_log_set_default_handler’? 
undefined reference to `g_log_get_debug_enabled'
```

**Comment by tsmetana** [comment]
It's not a version conflict: most probably Ubuntu 20.04 ships also too old glib version. `g_log_get_debug_enabled` [requires at least glib-2.72](https://docs.gtk.org/glib/func.log_get_debug_enabled.html)...

If you don't need the debugging logs (I suppose you don't) you can try to just comment out the `dump_buffer_data` function body [here](https://github.com/tsmetana/mpk3-settings/blob/master/src/device.c#L32-L45) and I guess I should add one more version check in the autoconf script.

**Comment by IOTeule** [comment]
Really thx for fast response ! Much appreciated.
I made progress, it compiled and I installed  by
```
make install
```
but the call 
```
mpk3-settings
```
leads to error

```
mpk3-settings: error while loading shared libraries: librtmidi.so.7: cannot open shared object file: No such file or directory
```
So I guess, rtmidi version is found, but not istalled correctly ?
I build rtmidi (id=6ad594f077e9d4991c8d050f3ded28b4964b58f3) in subfolder to mpk3-settings and also made make install ...

```
sudo apt list --installed | grep librtmidi*
librtmidi-dev/focal,now 3.0.0~ds1-2build1 amd64  [installiert]
librtmidi4/focal,now 3.0.0~ds1-2build1 amd64  [Installiert,automatisch]
```

Is there apt command to install newer version of librtmidi  ?

**Comment by tsmetana** [comment]
The error is from the linker that can't find the new rtmidi library you compiled. Find where the librtmidi.so.7 file is (`/usr/local/lib` or `/usr/local/lib64` might be good candidates) and then you may try to start the program with `LD_LIBRARY_PATH=<directory where the new library is> ./mpk3-settings`.

**Comment by IOTeule** [comment]
Hi, really thx a lot, at least it started, but does not find the device

```
** (mpk3-settings:24059): CRITICAL **: 22:22:51.948: No MPKmini MK3 device found
```

**Comment by tsmetana** [comment]
Run `lsusb -v` and check the output. You should see something like this in the output:
```
Bus 004 Device 007: ID 09e8:0049 AKAI  Professional M.I. Corp. [unknown]
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 [unknown]
  bDeviceSubClass         0 [unknown]
  bDeviceProtocol         0 
  bMaxPacketSize0        32
  idVendor           0x09e8 AKAI  Professional M.I. Corp.
  idProduct          0x0049 [unknown]
  bcdDevice            2.00
  iManufacturer           1 AKAI
  iProduct                2 MPK mini 3
  iSerial                 0 
  bNumConfigurations      1
```
If you can't see any MPK mini 3 MIDI device, then I can't really help.

**Comment by IOTeule** [comment]
Thx for supporting, I really enjoy your project and it would be great to see it working somehow.
Seems to be wrong product type ?
```
Bus 001 Device 006: ID 09e8:0045 AKAI  Professional M.I. Corp. MPK Mini Mk II
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x09e8 AKAI  Professional M.I. Corp.
  idProduct          0x0045 
  bcdDevice            2.00
  iManufacturer           1 
  iProduct                2 
  iSerial                 3 
  bNumConfigurations      1
```

**Comment by tsmetana** [comment]
Yup. I'm sorry to disappoint you, but you have a different device indeed (MPK Mini Mk II). Even though the devices are similar, they're not the same and since I don't have access to the Mk II version I don't know how different the MIDI messages are and what would it take to add support for it.

**Comment by IOTeule** [comment]
Ohh, really sorry for not having noticed this before.
So your support is even more appreciated.
Would you like to build an **MPK Mini Mk II** version together ?
I would like to support your project

**Comment by IOTeule** [comment]
Ohh, really sorry for not having noticed this before.
So your support is even more appreciated.
Would you like to build an **MPK Mini Mk II** version together ?
I would like to support your project

**Comment by tsmetana** [comment]
The most important file in the repo is the [header file with the magic constants](https://github.com/tsmetana/mpk3-settings/blob/master/src/message.h) for the MIDI SysEx messages. I got these by sniffing the USB packets sent by the original AKAI application in Windows (in this case it was easy -- there are harder nuts to crack). For MPK Mk II this has been done already and there are other projects on github suppporting that device, so you may take a look.

The message constants are different for Mk II, since the features of the devices differ -- Mk 3 has display that shows names of programs, knob names, uses different constants in the SysEx "header", etc. The UI is quite tightly coupled with these magic numbers and features currently. Even though I can imagine ways to support both the MPK mini keyboards or just create similar standalone application for Mk II, it is quite difficult for me without having the real hardware: You might have noticed the recent PRs -- I made mistakes in features I don't use (joystick dual CC) even when I have the hardware at hand.

On the other hand: feel free to fork this project and start tinkering: update the file with the SysEx constants, remove the UI elements you don't need... It's fun if you're into these kind of things. :)
