### ISSUE TITLE
Flatpak integration

### ISSUE THREAD

**Issue by soyersoyer** [tsmetana/mpk3-settings#14]
I think it would be good to install this app from flathub. What do you think? I can help to create a manifest file if needed.

**Comment by tsmetana** [comment]
I saw this coming... :) If somebody wishes to create and  maintain flatpak I'm certainly not against it. I myself don't use flatpaks, avoid doing so and in general don't care about them.

**Comment by soyersoyer** [comment]
Okey, no problem. I can create and maintain a flatpak.
But it will be easier to package if there are versions of this program.
Could you add a version tag (0.1.0 or 0.2.0?) to the HEAD?

**Comment by tsmetana** [comment]
Done.
