### ISSUE TITLE
C compiler cannot create executable

### ISSUE THREAD

**Issue by pennettafra** [tsmetana/mpk3-settings#4]
good morning,

unfortunately autogen is not able to compile on Mint 20.2
here's the config.log report, thank you in advance

=======================================================

This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by mpk3-settings configure 0.1, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ ./configure 

## ----------- ##

configure:2111: checking for a BSD-compatible install

configure:2179: result: /usr/bin/install -c

configure:2190: checking whether build environment is sane

configure:2245: result: yes

configure:2394: checking for a thread-safe mkdir -p

configure:2433: result: /usr/bin/mkdir -p

configure:2440: checking for gawk

configure:2456: found /usr/bin/gawk

configure:2467: result: gawk

configure:2478: checking whether make sets $(MAKE)

configure:2500: result: yes

configure:2529: checking whether make supports nested variables

configure:2546: result: yes

configure:2679: checking whether make supports the include directive

configure:2694: make -f confmf.GNU && cat confinc.out
this is the am__doit target

configure:2697: $? = 0

configure:2716: result: yes (GNU style)

configure:2786: checking for gcc

configure:2802: found /usr/bin/gcc

configure:2813: result: gcc

configure:3042: checking for C compiler version

configure:3051: gcc --version >&5
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:3062: $? = 0

configure:3051: gcc -v >&5
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu

Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.4.0-1ubuntu1~20.04.1' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-Av3uEd/gcc-9-9.4.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix

gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1) 

configure:3062: $? = 0

configure:3051: gcc -V >&5

gcc: error: unrecognized command line option '-V'

gcc: fatal error: no input files

compilation terminated.

configure:3062: $? = 1

configure:3051: gcc -qversion >&5

gcc: error: unrecognized command line option '-qversion'; did you mean '--version'?

gcc: fatal error: no input files

compilation terminated.

configure:3062: $? = 1

configure:3082: checking whether the C compiler works

configure:3104: gcc    conftest.c  >&5

/usr/bin/ld: cannot find Scrt1.o: No such file or directory

/usr/bin/ld: cannot find crti.o: No such file or directory

collect2: error: ld returned 1 exit status

configure:3108: $? = 1

configure:3146: result: no

configure: failed program was:

| /* confdefs.h */

| #define PACKAGE_NAME "mpk3-settings"

| #define PACKAGE_TARNAME "mpk3-settings"

| #define PACKAGE_VERSION "0.1"

| #define PACKAGE_STRING "mpk3-settings 0.1"

| #define PACKAGE_BUGREPORT ""

| #define PACKAGE_URL ""

| #define PACKAGE "mpk3-settings"

| #define VERSION "0.1"

| /* end confdefs.h.  */

| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }

configure:3151: error: in `/home/fra/Scrivania/1':

configure:3153: error: C compiler cannot create executables

See `config.log' for more details

## ---------------- ##

ac_cv_env_CC_set=

ac_cv_env_CC_value=

ac_cv_env_CFLAGS_set=

ac_cv_env_CFLAGS_value=

ac_cv_env_CPPFLAGS_set=

ac_cv_env_CPPFLAGS_value=

ac_cv_env_CPP_set=

ac_cv_env_CPP_value=

ac_cv_env_GTK_CFLAGS_set=

ac_cv_env_GTK_CFLAGS_value=

ac_cv_env_GTK_LIBS_set=

ac_cv_env_GTK_LIBS_value=

ac_cv_env_LDFLAGS_set=

ac_cv_env_LDFLAGS_value=

ac_cv_env_LIBS_set=

ac_cv_env_LIBS_value=

ac_cv_env_PKG_CONFIG_LIBDIR_set=

ac_cv_env_PKG_CONFIG_LIBDIR_value=

ac_cv_env_PKG_CONFIG_PATH_set=

ac_cv_env_PKG_CONFIG_PATH_value=

ac_cv_env_PKG_CONFIG_set=

ac_cv_env_PKG_CONFIG_value=

ac_cv_env_RTMIDI4_CFLAGS_set=

ac_cv_env_RTMIDI4_CFLAGS_value=

ac_cv_env_RTMIDI4_LIBS_set=

ac_cv_env_RTMIDI4_LIBS_value=

ac_cv_env_RTMIDI5_CFLAGS_set=

ac_cv_env_RTMIDI5_CFLAGS_value=

ac_cv_env_RTMIDI5_LIBS_set=

ac_cv_env_RTMIDI5_LIBS_value=

ac_cv_env_build_alias_set=

ac_cv_env_build_alias_value=

ac_cv_env_host_alias_set=

ac_cv_env_host_alias_value=

ac_cv_env_target_alias_set=

ac_cv_env_target_alias_value=

ac_cv_path_install='/usr/bin/install -c'

ac_cv_path_mkdir=/usr/bin/mkdir

ac_cv_prog_AWK=gawk

ac_cv_prog_ac_ct_CC=gcc

ac_cv_prog_make_make_set=yes

am_cv_make_support_nested_variables=yes

## ----------------- ##

ACLOCAL='${SHELL} /home/fra/Scrivania/1/missing aclocal-1.16'

AMDEPBACKSLASH='\'

AMDEP_FALSE='#'

AMDEP_TRUE=''

AMTAR='$${TAR-tar}'

AM_BACKSLASH='\'

AM_DEFAULT_V='$(AM_DEFAULT_VERBOSITY)'

AM_DEFAULT_VERBOSITY='1'

AM_V='$(V)'

AUTOCONF='${SHELL} /home/fra/Scrivania/1/missing autoconf'

AUTOHEADER='${SHELL} /home/fra/Scrivania/1/missing autoheader'

AUTOMAKE='${SHELL} /home/fra/Scrivania/1/missing automake-1.16'

AWK='gawk'

BUILD_DATE=''

CC='gcc'

CCDEPMODE=''

CFLAGS=''

CPP=''

CPPFLAGS=''

CYGPATH_W='echo'

DEFS=''

DEPDIR='.deps'

ECHO_C=''

ECHO_N='-n'

ECHO_T=''

EGREP=''

EXEEXT=''

GREP=''

GTK_CFLAGS=''

GTK_LIBS=''

INSTALL_DATA='${INSTALL} -m 644'

INSTALL_PROGRAM='${INSTALL}'

INSTALL_SCRIPT='${INSTALL}'

INSTALL_STRIP_PROGRAM='$(install_sh) -c -s'

LDFLAGS=''

LIBOBJS=''

LIBS=''

LTLIBOBJS=''

MAKEINFO='${SHELL} /home/fra/Scrivania/1/missing makeinfo'

MKDIR_P='/usr/bin/mkdir -p'

OBJEXT=''

PACKAGE='mpk3-settings'

PACKAGE_BUGREPORT=''

PACKAGE_NAME='mpk3-settings'

PACKAGE_STRING='mpk3-settings 0.1'

PACKAGE_TARNAME='mpk3-settings'

PACKAGE_URL=''

PACKAGE_VERSION='0.1'

PATH_SEPARATOR=':'

PKG_CONFIG=''

PKG_CONFIG_LIBDIR=''

PKG_CONFIG_PATH=''

RTMIDI4_CFLAGS=''

RTMIDI4_LIBS=''

RTMIDI5_CFLAGS=''

RTMIDI5_LIBS=''

RTMIDI_CFLAGS=''

RTMIDI_LIBS=''

SET_MAKE=''

SHELL='/bin/bash'

STRIP=''

VERSION='0.1'

ac_ct_CC='gcc'

am__EXEEXT_FALSE=''

am__EXEEXT_TRUE=''

am__fastdepCC_FALSE=''

am__fastdepCC_TRUE=''

am__include='include'

am__isrc=''

am__leading_dot='.'

am__nodep='_no'

am__quote=''

am__tar='$${TAR-tar} chof - "$$tardir"'

am__untar='$${TAR-tar} xf -'

bindir='${exec_prefix}/bin'

build_alias=''

datadir='${datarootdir}'

datarootdir='${prefix}/share'

docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'

dvidir='${docdir}'

exec_prefix='NONE'

host_alias=''

htmldir='${docdir}'

includedir='${prefix}/include'

infodir='${datarootdir}/info'

install_sh='${SHELL} /home/fra/Scrivania/1/install-sh'

libdir='${exec_prefix}/lib'

libexecdir='${exec_prefix}/libexec'

localedir='${datarootdir}/locale'

localstatedir='${prefix}/var'

mandir='${datarootdir}/man'

mkdir_p='$(MKDIR_P)'

oldincludedir='/usr/include'

pdfdir='${docdir}'

prefix='NONE'

program_transform_name='s,x,x,'

psdir='${docdir}'

runstatedir='${localstatedir}/run'

sbindir='${exec_prefix}/sbin'

sharedstatedir='${prefix}/com'

sysconfdir='${prefix}/etc'

target_alias=''

## ----------- ##

/* confdefs.h */

#define PACKAGE_NAME "mpk3-settings"

#define PACKAGE_TARNAME "mpk3-settings"

#define PACKAGE_VERSION "0.1"

#define PACKAGE_STRING "mpk3-settings 0.1"

#define PACKAGE_BUGREPORT ""

#define PACKAGE_URL ""

#define PACKAGE "mpk3-settings"

#define VERSION "0.1

**Comment by tsmetana** [comment]
How did you create the `configure` script (exactly)?

**Comment by pennettafra** [comment]
I've extracted the files into home then

$ autoreconf -i
$ ./configure
$ make

**Comment by tsmetana** [comment]
This suggests there's something wrong with your system:
```
/usr/bin/ld: cannot find Scrt1.o: No such file or directory
/usr/bin/ld: cannot find crti.o: No such file or directory
collect2: error: ld returned 1 exit status
```
Can you compile and link any C program at all?

**Comment by pennettafra** [comment]
thank you in advance,

I've taken a better look and configure gives this message

checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for GTK... yes
checking for RTMIDI5... no
checking for RTMIDI4... no
configure: error: Package requirements (rtmidi >= 4.0.0) were not met:


So the trouble may be in RTMIDI, which is already installed:
"Requirement already satisfied: python-rtmidi in /usr/lib/python3/dist-packages (1.2.1)"

How can I upgrade to rtmidi version 4?

**Comment by tsmetana** [comment]
I'm sorry I don't know Mint linux. If it's similar to Debian then I assume you need `librtmidi-dev` package. But I'm really not sure. Sorry.

**Comment by ndim** [comment]
[Mint](http://packages.linuxmint.com/search.php?release=any&section=any&keyword=rtmidi) appears to be based on [Ubuntu](https://packages.ubuntu.com/search?keywords=rtmidi) which is based on [Debian](https://packages.debian.org/search?keywords=rtmidi), but I cannot find any Linux Mint results for rtmidi on the Linux Mint packages page.

[repology.org](https://repology.org/project/rtmidi/versions) does not list Linux Mint either, so it cannot help any further.

So if I was sat in front of a Linux Mint system I would hope that Linux Mint did not remove the package and use the standard Debian `sudo apt install librtmidi-dev` command.

**Comment by ndim** [comment]
> I've taken a better look and configure gives this message
> 
> checking for gcc... (cached) gcc checking whether we are using the GNU C compiler... (cached) yes checking whether gcc accepts -g... (cached) yes checking for gcc option to accept ISO C89... (cached) none needed checking whether gcc understands -c and -o together... (cached) yes checking dependency style of gcc... (cached) gcc3 checking for pkg-config... /usr/bin/pkg-config checking pkg-config is at least version 0.9.0... yes checking for GTK... yes checking for RTMIDI5... no checking for RTMIDI4... no configure: error: Package requirements (rtmidi >= 4.0.0) were not met:

Hmm. What *is* it with your postings and adding and removing newlines?

> So the trouble may be in RTMIDI, which is already installed: "Requirement already satisfied: python-rtmidi in /usr/lib/python3/dist-packages (1.2.1)"
> 
> How can I upgrade to rtmidi version 4?

You do not need to "upgrade to rtmidi version 4". You need to actually install the development package. The python package probably just uses the rtmidi library in whatever version (probably 4 or 5, which means package `librtmidi5` for version 4, and `librtmidi6` for version 5), but that does not mean the development part of the rtmidi library (package `librtmidi-dev`) is installed.

So do install the `librtmidi-dev` package, and then re-run `configure`.

**Comment by pennettafra** [comment]
Thank you for your advice, I cannot get librtmidi-dev now  because is unavailable on my mint release, I'll let you know

**Comment by tsmetana** [comment]
Hello. Since the issue has nothing to do with mpk3-settings but rather Mint packaging, I'm closing the issue. I think the stackoverflow thread is more suitable for the discussion eventually.
