### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by peter9370** [tsmetana/mpk3-settings#7]
I hit a problem with building this:

make[2]: Entering directory '/usr/local/src/mpk3-settings/mpk3-settings/src'
gcc -Wall -g    -o mpk3-settings main.o app_win.o presets.o device.o file.o -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lrtmidi -ljack -lpthread -lasound 
/usr/bin/ld: device.o: in function `dump_buffer_data':
/usr/local/src/mpk3-settings/mpk3-settings/src/device.c:34: undefined reference to `g_log_get_debug_enabled'

As far as I can figure it out,  g_log_get_debug_enabled was only introduced in glib 2.72  - I'm using devuan chimaera (== debian bullseye without systemd) which uses glib 2.66.  

I believe the next version of devuan will use glib 2.74, so I'll try this again when it's available.

**Comment by tsmetana** [comment]
Hi. Yes, bookworm tells me it has glib 2.74.6. However if you want to compile it, just delete the offending call from [device.c](https://github.com/tsmetana/mpk3-settings/blob/master/src/device.c#L34-L35) or wrap it with `#ifndef GLIB_VERSION_2_72`. It's there just for cosmetic reasons.

**Comment by peter9370** [comment]
Thanks for that - I'll make that modification and try the build again: I'll report back on how it goes.

The next version of devuan (codenamed daedalus, and based on debian bookworm) is in the pipeline - but hasn't been announced as a stable release as yet. I'm intending to try it out fairly soon.

**Comment by peter9370** [comment]
I commented out the call to g_log_get_debug_enabled, and the build now completes successfully and the program runs fine: it seems to have picked up my MPK mini without a problem.

**Comment by tsmetana** [comment]
Sounds good. I'll close the issue for now.
