### ISSUE TITLE
autoreconf: error: aclocal failed with exit status: 2

### ISSUE THREAD

**Issue by yeldarb1983** [tsmetana/mpk3-settings#8]
Running Fedora 37 with KDE plasma. trying to set this up for an akai mpk mini (not the 3[edit: ignore this bit, apparently, mine is the III, it's just the black model). I realize it's a slightly different model, but I haven't even gotten the software built yet.

here's the bash output, let me know if you need anything else:

(base) [yeldarb1983@fedora mpk3-settings]$ autoreconf -i
Can't exec "aclocal": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 274.
autoreconf: error: aclocal failed with exit status: 2

Also, if there's any way I can help with my specific keyboard (extracting raw data, etc), feel free to let me know. I suck at coding, but I'm always happy to help however I can, and I can follow basic instructions, lol.

**Comment by tsmetana** [comment]
Hello. Sorry for the slow response. aclocal is part of the automake package, are you sure you have automake installed?
