### ISSUE TITLE
The program doesnt find the device even if connected

### ISSUE THREAD

**Issue by MattiaDallaCosta** [tsmetana/mpk3-settings#9]
The title is kind of self-explanatory, after building the repo I run ./mpk3-settings  in the src/ directory but the program tells me that it can't find the device and then crashes.
<sub>** (mpk3-settings:717355): CRITICAL **: 13:33:21.458: No MPKmini MK3 device found </sub>
this is the output of the program.
I checked using lsusb if the device was actually detected by the system and it is
output fo lsusb:
<sub>Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 011: ID 09e8:1049 AKAI  Professional M.I. Corp. MPK mini 3
Bus 003 Device 010: ID 05e3:0610 Genesys Logic, Inc. Hub
Bus 003 Device 005: ID 27c6:532d Shenzhen Goodix Technology Co.,Ltd. Fingerprint
Bus 003 Device 003: ID 8087:0026 Intel Corp. AX201 Bluetooth
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 004: ID 05e3:0626 Genesys Logic, Inc. Hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub</sub>
Where the 2nd device listed is the keyboard
Maybe the problem stems from the fact that I am using a USB hub (the 7th device in the list above) to connect the keyboard to the PC since I don't have USB-A but only USB-C, but I didn't put that much thought into that

**Comment by tsmetana** [comment]
Hello. Could you please start the program with `G_MESSAGES_DEBUG=all` env variable set? It will spit out lot of messages but the first two look like this on my system:
```
** (mpk3-settings:5130): DEBUG: 14:36:52.126: Found 3 MIDI devices
** (mpk3-settings:5130): DEBUG: 14:36:52.126: Using device 2: MPK mini 3:MPK mini 3 MIDI 1 32:0
```
This should tell us whether it's the RTMidi library I rely on for the device discovery, or I fail to find the correct device.
